#!/bin/busybox sh

# Do initial environment preparation
/bin/busybox --install
mkdir -p /dev
mount -t devtmpfs none /dev/

echo "[sbnb] Preparing environment ..." > /dev/kmsg
mkdir -p /proc
mkdir -p /sys

mount -t proc none /proc
mount -t sysfs none /sys

echo "[sbnb] Mounting squashfs root filesystem ..." > /dev/kmsg
mkdir /upper
mkdir /work
mkdir /rootfs
mkdir /lower
mount -t squashfs /rootfs.squashfs /lower

mount -t overlay -o rw,lowerdir=/lower,upperdir=/upper,workdir=/work overlay /rootfs/

echo "[sbnb] Switching to squashfs root filesystem ..." > /dev/kmsg
exec switch_root /rootfs /sbin/init
