---

- hosts: "{{ lookup('ansible.builtin.env', 'SBNB_HOSTS') }}"
  gather_facts: true
  ignore_unreachable: true

  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: Install Nvidia kernel modules and utils
      vars:
        DRIVER_BRANCH: "570"

      apt:
        pkg:
        - nvidia-utils-{{ DRIVER_BRANCH }}-server
        - linux-modules-nvidia-{{ DRIVER_BRANCH }}-server-open-{{ ansible_kernel }}
