---

- hosts: "{{ lookup('ansible.builtin.env', 'SBNB_HOSTS') }}"
  gather_facts: false
  ignore_unreachable: true

  tasks:
    - ping:

    - name: Initialize an empty arguments list
      set_fact:
        vm_id: "{{ inventory_hostname + '-vm-' + 99999999 | random | to_uuid }}"
        args: ""

    - name: Download configuration scripts
      get_url:
        url: "https://raw.githubusercontent.com/sbnb-io/sbnb/refs/heads/main/scripts/{{ item }}"
        dest: /dev/shm/
        mode: u+x
      loop:
        - sbnb-configure-system.sh
        - sbnb-configure-networking.sh
        - sbnb-configure-storage.sh
        - sbnb-start-vm.sh

    - name: Execute host configuration script
      command: sh /dev/shm/sbnb-configure-system.sh

    - name: If VM json config exist
      local_action: stat path=sbnb-example-vm.json
      connection: local
      register: file

    - name: Copy VM config if it exists
      copy: src=sbnb-example-vm.json dest=/dev/shm/sbnb-example-vm.json
      when: file.stat.exists

    - name: Set args
      set_fact:
        args: "{{ args + '-f /dev/shm/sbnb-example-vm.json' }}"
      when: file.stat.exists

    - name: Print VM info
      ansible.builtin.debug:
        msg: VM id "{{ vm_id }}"

    - name: Start VM using qemu container
      docker_container:
        name: "{{ vm_id }}"
        image: sbnb/svsm
        pull: always
        privileged: true
        network_mode: host
        devices:
          - /dev/kvm:/dev/kvm
          - /dev/sev:/dev/sev
        volumes:
          - /sys:/sys
          - /dev:/dev
          - /dev/shm:/dev/shm
          - /mnt/sbnb-data:/mnt/sbnb-data
          - /dev/shm/sbnb-start-vm.sh:/dev/shm/sbnb-start-vm.sh
        env:
          SBNB_VM_TSKEY: "{{ lookup('ansible.builtin.env', 'SBNB_VM_TSKEY') }}"
          SBNB_VM_VCPU: "{{ lookup('ansible.builtin.env', 'SBNB_VM_VCPU') }}"
          SBNB_VM_MEM: "{{ lookup('ansible.builtin.env', 'SBNB_VM_MEM') }}"
          SBNB_VM_IMAGE_SIZE: "{{ lookup('ansible.builtin.env', 'SBNB_VM_IMAGE_SIZE') }}"
          SBNB_VM_ATTACH_GPUS: "{{ lookup('ansible.builtin.env', 'SBNB_VM_ATTACH_GPUS') }}"
          SBNB_VM_ATTACH_PCIE_DEVICES: "{{ lookup('ansible.builtin.env', 'ATTACH_PCIE_DEVICES') }}"
          SBNB_VM_CONFIDENTIAL_COMPUTING: "{{ lookup('ansible.builtin.env', 'CONFIDENTIAL_COMPUTING') }}"
          SBNB_VM_HOSTNAME: "{{ vm_id }}"

        command: /dev/shm/sbnb-start-vm.sh {{ args }}
